import type { LottieObject } from "@/types";

export const loser2Base: LottieObject = {
  v: "5.12.1",
  fr: 30,
  ip: 0,
  op: 41,
  w: 900,
  h: 1080,
  nm: "loser02_character01",
  ddd: 0,
  assets: [
    {
      id: "comp_0",
      nm: "tears",
      fr: 30,
      layers: [
        {
          ddd: 0,
          ind: 1,
          ty: 4,
          nm: "right",
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: { a: 0, k: 0, ix: 10 },
            p: { a: 0, k: [465.672, 371.736, 0], ix: 2, l: 2 },
            a: { a: 0, k: [0, 0, 0], ix: 1, l: 2 },
            s: { a: 0, k: [-100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          sy: [
            {
              c: {
                a: 0,
                k: [0.113725498319, 0.113725498319, 0.105882361531, 1],
                ix: 2,
              },
              s: { a: 0, k: 3, ix: 3 },
              ty: 0,
              nm: "Stroke",
            },
          ],
          shapes: [
            {
              ty: "gr",
              it: [
                {
                  ind: 0,
                  ty: "sh",
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [0, 0],
                        [137.705, -11.412],
                        [0, -173.003],
                      ],
                      o: [
                        [0, 0],
                        [-181, 15],
                        [0, 107],
                      ],
                      v: [
                        [11, -190],
                        [-149, -306],
                        [-293, 209],
                      ],
                      c: false,
                    },
                    ix: 2,
                  },
                  nm: "Path 1",
                  mn: "ADBE Vector Shape - Group",
                  hd: false,
                },
                {
                  ty: "st",
                  c: {
                    a: 0,
                    k: [0.384313762188, 0.556862771511, 0.870588302612, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 15, ix: 5 },
                  lc: 2,
                  lj: 1,
                  ml: 4,
                  bm: 0,
                  d: [
                    {
                      n: "d",
                      nm: "dash",
                      v: { a: 0, k: 0, ix: 1 },
                    },
                    {
                      n: "g",
                      nm: "gap",
                      v: { a: 0, k: 70, ix: 2 },
                    },
                    {
                      n: "o",
                      nm: "offset",
                      v: {
                        a: 1,
                        k: [
                          {
                            i: { x: [0.833], y: [0.833] },
                            o: { x: [0.167], y: [0.167] },
                            t: 0,
                            s: [12],
                          },
                          { t: 40, s: [-268] },
                        ],
                        ix: 7,
                      },
                    },
                  ],
                  nm: "Stroke 1",
                  mn: "ADBE Vector Graphic - Stroke",
                  hd: false,
                },
                {
                  ty: "tr",
                  p: { a: 0, k: [0, 0], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: "Transform",
                },
              ],
              nm: "Shape 1",
              np: 3,
              cix: 2,
              bm: 0,
              ix: 1,
              mn: "ADBE Vector Group",
              hd: false,
            },
          ],
          ip: 0,
          op: 41,
          st: 0,
          ct: 1,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 2,
          ty: 4,
          nm: "left",
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: { a: 0, k: 0, ix: 10 },
            p: { a: 0, k: [396.474, 371.736, 0], ix: 2, l: 2 },
            a: { a: 0, k: [0, 0, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          sy: [
            {
              c: {
                a: 0,
                k: [0.113725498319, 0.113725498319, 0.105882361531, 1],
                ix: 2,
              },
              s: { a: 0, k: 3, ix: 3 },
              ty: 0,
              nm: "Stroke",
            },
          ],
          shapes: [
            {
              ty: "gr",
              it: [
                {
                  ind: 0,
                  ty: "sh",
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [0, 0],
                        [137.705, -11.412],
                        [0, -173.003],
                      ],
                      o: [
                        [0, 0],
                        [-181, 15],
                        [0, 107],
                      ],
                      v: [
                        [11, -190],
                        [-149, -306],
                        [-293, 209],
                      ],
                      c: false,
                    },
                    ix: 2,
                  },
                  nm: "Path 1",
                  mn: "ADBE Vector Shape - Group",
                  hd: false,
                },
                {
                  ty: "st",
                  c: {
                    a: 0,
                    k: [0.384313762188, 0.556862771511, 0.870588302612, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 15, ix: 5 },
                  lc: 2,
                  lj: 1,
                  ml: 4,
                  bm: 0,
                  d: [
                    {
                      n: "d",
                      nm: "dash",
                      v: { a: 0, k: 0, ix: 1 },
                    },
                    {
                      n: "g",
                      nm: "gap",
                      v: { a: 0, k: 70, ix: 2 },
                    },
                    {
                      n: "o",
                      nm: "offset",
                      v: {
                        a: 1,
                        k: [
                          {
                            i: { x: [0.833], y: [0.833] },
                            o: { x: [0.167], y: [0.167] },
                            t: 0,
                            s: [12],
                          },
                          { t: 40, s: [-268] },
                        ],
                        ix: 7,
                      },
                    },
                  ],
                  nm: "Stroke 1",
                  mn: "ADBE Vector Graphic - Stroke",
                  hd: false,
                },
                {
                  ty: "tr",
                  p: { a: 0, k: [0, 0], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: "Transform",
                },
              ],
              nm: "Shape 1",
              np: 3,
              cix: 2,
              bm: 0,
              ix: 1,
              mn: "ADBE Vector Group",
              hd: false,
            },
          ],
          ip: 0,
          op: 41,
          st: 0,
          ct: 1,
          bm: 0,
        },
      ],
    },
  ],
  layers: [
    {
      ddd: 0,
      ind: 1,
      ty: 0,
      nm: "tears",
      refId: "comp_0",
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: { a: 0, k: 0, ix: 10 },
        p: { a: 0, k: [450, 540, 0], ix: 2, l: 2 },
        a: { a: 0, k: [425, 450, 0], ix: 1, l: 2 },
        s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
      },
      ao: 0,
      w: 850,
      h: 900,
      ip: 0,
      op: 41,
      st: 0,
      bm: 0,
    },
  ],
  markers: [],
  props: {},
};

export const loserBase: LottieObject = {
  v: "5.12.1",
  fr: 30,
  ip: 0,
  op: 60,
  w: 900,
  h: 1080,
  nm: "loser_base",
  ddd: 0,
  assets: [],
  layers: [],
  markers: [],
  props: {},
};

export const loser5Base: LottieObject = {
  v: "5.12.1",
  fr: 30,
  ip: 0,
  op: 30,
  w: 1080,
  h: 500,
  nm: "loser05_base",
  ddd: 0,
  assets: [],
  layers: [],
  markers: [],
  props: {},
};
