import type { CharPartJson } from "@/lib/createrandomchar";

export const front_arm2: CharPartJson = {
  asset: [
    {
      id: "comp_1",
      nm: "front_arm",
      fr: 12,
      layers: [
        {
          ddd: 0,
          ind: 1,
          ty: 0,
          nm: "BRACO FRENTE",
          parent: 3,
          refId: "comp_2",
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: { a: 0, k: 12, ix: 10 },
            p: { a: 0, k: [-48, 25, 0], ix: 2, l: 2 },
            a: { a: 0, k: [912, 536, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          w: 1920,
          h: 1080,
          ip: 0,
          op: 10,
          st: -4,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 2,
          ty: 3,
          nm: "Null 4",
          sr: 1,
          ks: {
            o: { a: 0, k: 0, ix: 11 },
            r: { a: 0, k: 0, ix: 10 },
            p: {
              a: 1,
              k: [
                {
                  i: { x: 0.335, y: 0.335 },
                  o: { x: 0.665, y: 0.665 },
                  t: 0,
                  s: [960, 507.5, 0],
                  to: [0, 0, 0],
                  ti: [0, 0, 0],
                },
                {
                  i: { x: 0.335, y: 0.335 },
                  o: { x: 0.665, y: 0.665 },
                  t: 2,
                  s: [960, 507.5, 0],
                  to: [0, 0, 0],
                  ti: [0, 0, 0],
                },
                {
                  i: { x: 0.335, y: 0.335 },
                  o: { x: 0.665, y: 0.665 },
                  t: 4.8,
                  s: [960, 507.5, 0],
                  to: [0, 0, 0],
                  ti: [0, 0, 0],
                },
                { t: 9.60009765625, s: [960, 507.5, 0] },
              ],
              ix: 2,
              l: 2,
            },
            a: { a: 0, k: [0, 0, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          ip: 0,
          op: 10,
          st: -4,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 3,
          ty: 3,
          nm: "Null 1",
          parent: 2,
          sr: 1,
          ks: {
            o: { a: 0, k: 0, ix: 11 },
            r: { a: 0, k: 0, ix: 10 },
            p: {
              a: 1,
              k: [
                {
                  i: { x: 0.903, y: 1 },
                  o: { x: 0.556, y: 0 },
                  t: 0,
                  s: [0, -29, 0],
                  to: [0, 0, 0],
                  ti: [0, 0, 0],
                },
                {
                  i: { x: 0.667, y: 1 },
                  o: { x: 0.028, y: 0 },
                  t: 2.4,
                  s: [0, 21, 0],
                  to: [0, 0, 0],
                  ti: [0, 0, 0],
                },
                {
                  i: { x: 0.903, y: 1 },
                  o: { x: 0.556, y: 0 },
                  t: 4.8,
                  s: [0, -29, 0],
                  to: [0, 0, 0],
                  ti: [0, 0, 0],
                },
                {
                  i: { x: 0.484, y: 1 },
                  o: { x: 0.028, y: 0 },
                  t: 7.2,
                  s: [0, 21, 0],
                  to: [0, 0, 0],
                  ti: [0, 0, 0],
                },
                { t: 9.60009765625, s: [0, -29, 0] },
              ],
              ix: 2,
              l: 2,
            },
            a: { a: 0, k: [0, 0, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          ip: 0,
          op: 10,
          st: -4,
          bm: 0,
        },
      ],
    },
    {
      id: "comp_2",
      nm: "BRACO FRENTE",
      fr: 30,
      layers: [
        {
          ddd: 0,
          ind: 1,
          ty: 4,
          nm: "Mao 1 Outlines 3",
          parent: 9,
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: { a: 0, k: 13.982, ix: 10 },
            p: { a: 0, k: [62.025, 81.81, 0], ix: 2, l: 2 },
            a: { a: 0, k: [90.326, 88.608, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          shapes: [
            {
              ty: "gr",
              it: [
                {
                  ind: 0,
                  ty: "sh",
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [0, 0],
                        [16.826, -13.22],
                      ],
                      o: [
                        [0, 0],
                        [0, 0],
                      ],
                      v: [
                        [8.413, -23.924],
                        [-8.413, 23.924],
                      ],
                      c: false,
                    },
                    ix: 2,
                  },
                  nm: "Path 1",
                  mn: "ADBE Vector Shape - Group",
                  hd: false,
                },
                {
                  ty: "st",
                  c: {
                    a: 0,
                    k: [0.160784313725, 0.160784313725, 0.152941176471, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 3, ix: 5 },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: "Stroke 1",
                  mn: "ADBE Vector Graphic - Stroke",
                  hd: false,
                },
                {
                  ty: "tr",
                  p: { a: 0, k: [115.466, 104.895], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: "Transform",
                },
              ],
              nm: "Group 1",
              np: 2,
              cix: 2,
              bm: 0,
              ix: 1,
              mn: "ADBE Vector Group",
              hd: false,
            },
            {
              ty: "gr",
              it: [
                {
                  ind: 0,
                  ty: "sh",
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [0, 0],
                        [8.609, -5.783],
                      ],
                      o: [
                        [-2.446, -8.622],
                        [0, 0],
                      ],
                      v: [
                        [10.028, 7.159],
                        [-10.028, -1.376],
                      ],
                      c: false,
                    },
                    ix: 2,
                  },
                  nm: "Path 1",
                  mn: "ADBE Vector Shape - Group",
                  hd: false,
                },
                {
                  ty: "st",
                  c: {
                    a: 0,
                    k: [0.160784313725, 0.160784313725, 0.152941176471, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 3, ix: 5 },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: "Stroke 1",
                  mn: "ADBE Vector Graphic - Stroke",
                  hd: false,
                },
                {
                  ty: "tr",
                  p: { a: 0, k: [129.994, 108.283], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: "Transform",
                },
              ],
              nm: "Group 2",
              np: 2,
              cix: 2,
              bm: 0,
              ix: 2,
              mn: "ADBE Vector Group",
              hd: false,
            },
            {
              ty: "gr",
              it: [
                {
                  ind: 0,
                  ty: "sh",
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [-51.144, 30.377],
                        [0, 0],
                        [33.131, -16.434],
                        [53.001, 11.681],
                        [-1.565, 24.522],
                      ],
                      o: [
                        [0, 0],
                        [0, 0],
                        [0, 0],
                        [-53.001, -11.68],
                        [1.565, -24.522],
                      ],
                      v: [
                        [-16.696, -81.109],
                        [57.343, -38.416],
                        [49.695, 26.834],
                        [-8.695, 69.428],
                        [-81.261, 6.356],
                      ],
                      c: true,
                    },
                    ix: 2,
                  },
                  nm: "Path 1",
                  mn: "ADBE Vector Shape - Group",
                  hd: false,
                },
                {
                  ty: "st",
                  c: {
                    a: 0,
                    k: [0.160784313725, 0.160784313725, 0.152941176471, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 3, ix: 5 },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: "Stroke 1",
                  mn: "ADBE Vector Graphic - Stroke",
                  hd: false,
                },
                {
                  ty: "fl",
                  c: {
                    a: 0,
                    k: [0.913725550034, 0.298039215686, 0.36862745098, 1],
                    ix: 4,
                  },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  bm: 0,
                  nm: "Fill 1",
                  mn: "ADBE Vector Graphic - Fill",
                  hd: false,
                },
                {
                  ty: "tr",
                  p: { a: 0, k: [90.326, 88.608], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: "Transform",
                },
              ],
              nm: "Group 3",
              np: 3,
              cix: 2,
              bm: 0,
              ix: 3,
              mn: "ADBE Vector Group",
              hd: false,
            },
          ],
          ip: 0,
          op: 120,
          st: 0,
          ct: 1,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 2,
          ty: 4,
          nm: "Braço 1 Outlines 3",
          parent: 7,
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: { a: 0, k: 0, ix: 10 },
            p: { a: 0, k: [153.123, 71.032, 0], ix: 2, l: 2 },
            a: { a: 0, k: [157.781, 76.197, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          shapes: [
            {
              ty: "gr",
              it: [
                {
                  ind: 0,
                  ty: "sh",
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [0, -5.427],
                        [5.427, 0],
                        [0, 5.427],
                        [-5.427, 0],
                      ],
                      o: [
                        [0, 5.427],
                        [-5.427, 0],
                        [0, -5.427],
                        [5.427, 0],
                      ],
                      v: [
                        [9.827, 0],
                        [0, 9.827],
                        [-9.827, 0],
                        [0, -9.827],
                      ],
                      c: true,
                    },
                    ix: 2,
                  },
                  nm: "Path 1",
                  mn: "ADBE Vector Shape - Group",
                  hd: false,
                },
                {
                  ty: "st",
                  c: {
                    a: 0,
                    k: [0.160784313725, 0.160784313725, 0.152941176471, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 3, ix: 5 },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: "Stroke 1",
                  mn: "ADBE Vector Graphic - Stroke",
                  hd: false,
                },
                {
                  ty: "fl",
                  c: {
                    a: 0,
                    k: [0.733333333333, 0.694117647059, 0.709803921569, 1],
                    ix: 4,
                  },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  bm: 0,
                  nm: "Fill 1",
                  mn: "ADBE Vector Graphic - Fill",
                  hd: false,
                },
                {
                  ty: "tr",
                  p: { a: 0, k: [55.242, 55.24], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: "Transform",
                },
              ],
              nm: "Group 1",
              np: 3,
              cix: 2,
              bm: 0,
              ix: 1,
              mn: "ADBE Vector Group",
              hd: false,
            },
            {
              ty: "gr",
              it: [
                {
                  ind: 0,
                  ty: "sh",
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [0, -13.172],
                        [13.172, 0],
                        [0, 13.172],
                        [-13.173, 0],
                      ],
                      o: [
                        [0, 13.172],
                        [-13.173, 0],
                        [0, -13.172],
                        [13.172, 0],
                      ],
                      v: [
                        [23.851, 0],
                        [0, 23.85],
                        [-23.851, 0],
                        [0, -23.85],
                      ],
                      c: true,
                    },
                    ix: 2,
                  },
                  nm: "Path 1",
                  mn: "ADBE Vector Shape - Group",
                  hd: false,
                },
                {
                  ty: "st",
                  c: {
                    a: 0,
                    k: [0.160784313725, 0.160784313725, 0.152941176471, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 3, ix: 5 },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: "Stroke 1",
                  mn: "ADBE Vector Graphic - Stroke",
                  hd: false,
                },
                {
                  ty: "fl",
                  c: {
                    a: 0,
                    k: [0.937254961799, 0.921568687289, 0.917647118662, 1],
                    ix: 4,
                  },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  bm: 0,
                  nm: "Fill 1",
                  mn: "ADBE Vector Graphic - Fill",
                  hd: false,
                },
                {
                  ty: "tr",
                  p: { a: 0, k: [55.242, 55.24], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: "Transform",
                },
              ],
              nm: "Group 2",
              np: 3,
              cix: 2,
              bm: 0,
              ix: 2,
              mn: "ADBE Vector Group",
              hd: false,
            },
            {
              ty: "gr",
              it: [
                {
                  ind: 0,
                  ty: "sh",
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [0, -7.999],
                        [7.999, 0],
                        [0, 7.999],
                        [-7.998, 0],
                      ],
                      o: [
                        [0, 7.999],
                        [-7.998, 0],
                        [0, -7.999],
                        [7.999, 0],
                      ],
                      v: [
                        [14.483, 0],
                        [-0.001, 14.483],
                        [-14.483, 0],
                        [-0.001, -14.483],
                      ],
                      c: true,
                    },
                    ix: 2,
                  },
                  nm: "Path 1",
                  mn: "ADBE Vector Shape - Group",
                  hd: false,
                },
                {
                  ty: "st",
                  c: {
                    a: 0,
                    k: [0.160784313725, 0.160784313725, 0.152941176471, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 3, ix: 5 },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: "Stroke 1",
                  mn: "ADBE Vector Graphic - Stroke",
                  hd: false,
                },
                {
                  ty: "fl",
                  c: {
                    a: 0,
                    k: [0.733333333333, 0.694117647059, 0.709803921569, 1],
                    ix: 4,
                  },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  bm: 0,
                  nm: "Fill 1",
                  mn: "ADBE Vector Graphic - Fill",
                  hd: false,
                },
                {
                  ty: "tr",
                  p: { a: 0, k: [157.782, 76.197], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: "Transform",
                },
              ],
              nm: "Group 3",
              np: 3,
              cix: 2,
              bm: 0,
              ix: 3,
              mn: "ADBE Vector Group",
              hd: false,
            },
            {
              ty: "gr",
              it: [
                {
                  ind: 0,
                  ty: "sh",
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [0, -13.172],
                        [13.172, 0],
                        [0, 13.172],
                        [-13.173, 0],
                      ],
                      o: [
                        [0, 13.172],
                        [-13.173, 0],
                        [0, -13.172],
                        [13.172, 0],
                      ],
                      v: [
                        [23.851, 0],
                        [0, 23.85],
                        [-23.851, 0],
                        [0, -23.85],
                      ],
                      c: true,
                    },
                    ix: 2,
                  },
                  nm: "Path 1",
                  mn: "ADBE Vector Shape - Group",
                  hd: false,
                },
                {
                  ty: "st",
                  c: {
                    a: 0,
                    k: [0.160784313725, 0.160784313725, 0.152941176471, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 3, ix: 5 },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: "Stroke 1",
                  mn: "ADBE Vector Graphic - Stroke",
                  hd: false,
                },
                {
                  ty: "fl",
                  c: {
                    a: 0,
                    k: [0.937254961799, 0.921568687289, 0.917647118662, 1],
                    ix: 4,
                  },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  bm: 0,
                  nm: "Fill 1",
                  mn: "ADBE Vector Graphic - Fill",
                  hd: false,
                },
                {
                  ty: "tr",
                  p: { a: 0, k: [157.781, 76.197], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: "Transform",
                },
              ],
              nm: "Group 4",
              np: 3,
              cix: 2,
              bm: 0,
              ix: 4,
              mn: "ADBE Vector Group",
              hd: false,
            },
            {
              ty: "gr",
              it: [
                {
                  ind: 0,
                  ty: "sh",
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [3.912, 0],
                        [0.558, 0.11],
                        [0, 0],
                        [1.249, 1.864],
                        [-0.435, 2.201],
                        [-3.916, 0],
                        [-0.559, -0.111],
                        [0, 0],
                        [-0.715, -1.067],
                        [0.575, -2.914],
                      ],
                      o: [
                        [-0.542, 0],
                        [0, 0],
                        [-2.202, -0.435],
                        [-1.249, -1.863],
                        [0.765, -3.875],
                        [0.539, 0],
                        [0, 0],
                        [2.914, 0.575],
                        [0.716, 1.069],
                        [-0.765, 3.874],
                      ],
                      v: [
                        [50.817, 18.328],
                        [49.159, 18.163],
                        [-52.508, -1.915],
                        [-57.784, -5.43],
                        [-59.029, -11.642],
                        [-50.951, -18.328],
                        [-49.295, -18.162],
                        [52.368, 1.916],
                        [57.633, 5.435],
                        [58.888, 11.643],
                      ],
                      c: true,
                    },
                    ix: 2,
                  },
                  nm: "Path 1",
                  mn: "ADBE Vector Shape - Group",
                  hd: false,
                },
                {
                  ty: "st",
                  c: {
                    a: 0,
                    k: [0.160784313725, 0.160784313725, 0.152941176471, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 3, ix: 5 },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: "Stroke 1",
                  mn: "ADBE Vector Graphic - Stroke",
                  hd: false,
                },
                {
                  ty: "fl",
                  c: {
                    a: 0,
                    k: [0.552941176471, 0.545098039216, 0.63137254902, 1],
                    ix: 4,
                  },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  bm: 0,
                  nm: "Fill 1",
                  mn: "ADBE Vector Graphic - Fill",
                  hd: false,
                },
                {
                  ty: "tr",
                  p: { a: 0, k: [106.584, 65.719], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: "Transform",
                },
              ],
              nm: "Group 5",
              np: 3,
              cix: 2,
              bm: 0,
              ix: 5,
              mn: "ADBE Vector Group",
              hd: false,
            },
            {
              ty: "gr",
              it: [
                {
                  ind: 0,
                  ty: "sh",
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [0, 0],
                        [1.573, 0.311],
                        [0, 0],
                        [3.611, 5.388],
                        [-1.256, 6.362],
                        [-11.535, 0],
                        [-1.574, -0.311],
                        [0, 0],
                        [2.594, -13.135],
                        [11.531, 0],
                      ],
                      o: [
                        [-1.582, 0],
                        [0, 0],
                        [-6.363, -1.256],
                        [-3.611, -5.387],
                        [2.242, -11.349],
                        [1.578, 0],
                        [0, 0],
                        [13.135, 2.593],
                        [-2.241, 11.348],
                        [0, 0],
                      ],
                      v: [
                        [50.216, 34.328],
                        [45.461, 33.859],
                        [-56.208, 13.781],
                        [-71.674, 3.479],
                        [-75.325, -14.742],
                        [-51.549, -34.328],
                        [-46.799, -33.859],
                        [54.87, -13.781],
                        [73.987, 14.744],
                        [50.217, 34.328],
                      ],
                      c: true,
                    },
                    ix: 2,
                  },
                  nm: "Path 1",
                  mn: "ADBE Vector Shape - Group",
                  hd: false,
                },
                {
                  ty: "st",
                  c: {
                    a: 0,
                    k: [0.160784313725, 0.160784313725, 0.152941176471, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 3, ix: 5 },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: "Stroke 1",
                  mn: "ADBE Vector Graphic - Stroke",
                  hd: false,
                },
                {
                  ty: "fl",
                  c: {
                    a: 0,
                    k: [0.733333333333, 0.694117647059, 0.709803921569, 1],
                    ix: 4,
                  },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  bm: 0,
                  nm: "Fill 1",
                  mn: "ADBE Vector Graphic - Fill",
                  hd: false,
                },
                {
                  ty: "tr",
                  p: { a: 0, k: [107.183, 65.719], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: "Transform",
                },
              ],
              nm: "Group 6",
              np: 3,
              cix: 2,
              bm: 0,
              ix: 6,
              mn: "ADBE Vector Group",
              hd: false,
            },
            {
              ty: "gr",
              it: [
                {
                  ind: 0,
                  ty: "sh",
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [0, 0],
                        [4.738, -23.992],
                        [-23.992, -4.738],
                        [0, 0],
                        [-4.738, 23.992],
                        [23.992, 4.738],
                      ],
                      o: [
                        [-23.992, -4.738],
                        [-4.738, 23.992],
                        [0, 0],
                        [23.993, 4.738],
                        [4.738, -23.992],
                        [0, 0],
                      ],
                      v: [
                        [-42.255, -53.481],
                        [-94.276, -18.618],
                        [-59.413, 33.403],
                        [42.255, 53.481],
                        [94.276, 18.618],
                        [59.414, -33.403],
                      ],
                      c: true,
                    },
                    ix: 2,
                  },
                  nm: "Path 1",
                  mn: "ADBE Vector Shape - Group",
                  hd: false,
                },
                {
                  ty: "st",
                  c: {
                    a: 0,
                    k: [0.160784313725, 0.160784313725, 0.152941176471, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 3, ix: 5 },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: "Stroke 1",
                  mn: "ADBE Vector Graphic - Stroke",
                  hd: false,
                },
                {
                  ty: "fl",
                  c: {
                    a: 0,
                    k: [0.552941176471, 0.545098039216, 0.63137254902, 1],
                    ix: 4,
                  },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  bm: 0,
                  nm: "Fill 1",
                  mn: "ADBE Vector Graphic - Fill",
                  hd: false,
                },
                {
                  ty: "tr",
                  p: { a: 0, k: [106.514, 65.719], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: "Transform",
                },
              ],
              nm: "Group 7",
              np: 3,
              cix: 2,
              bm: 0,
              ix: 7,
              mn: "ADBE Vector Group",
              hd: false,
            },
          ],
          ip: 0,
          op: 120,
          st: 0,
          ct: 1,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 3,
          ty: 4,
          nm: "Antebraço 1 Outlines 3",
          parent: 8,
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: { a: 0, k: -0.048, ix: 10 },
            p: { a: 0, k: [103.024, 52.787, 0], ix: 2, l: 2 },
            a: { a: 0, k: [108.034, 57.867, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          shapes: [
            {
              ty: "gr",
              it: [
                {
                  ind: 0,
                  ty: "sh",
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [5.182, 1.612],
                        [-1.611, 5.183],
                        [-5.182, -1.612],
                        [1.611, -5.182],
                      ],
                      o: [
                        [-5.182, -1.612],
                        [1.612, -5.182],
                        [5.182, 1.611],
                        [-1.612, 5.183],
                      ],
                      v: [
                        [-2.918, 9.383],
                        [-9.384, -2.918],
                        [2.918, -9.384],
                        [9.384, 2.918],
                      ],
                      c: true,
                    },
                    ix: 2,
                  },
                  nm: "Path 1",
                  mn: "ADBE Vector Shape - Group",
                  hd: false,
                },
                {
                  ty: "st",
                  c: {
                    a: 0,
                    k: [0.160784313725, 0.160784313725, 0.152941176471, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 3, ix: 5 },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: "Stroke 1",
                  mn: "ADBE Vector Graphic - Stroke",
                  hd: false,
                },
                {
                  ty: "fl",
                  c: {
                    a: 0,
                    k: [0.552941176471, 0.545098039216, 0.63137254902, 1],
                    ix: 4,
                  },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  bm: 0,
                  nm: "Fill 1",
                  mn: "ADBE Vector Graphic - Fill",
                  hd: false,
                },
                {
                  ty: "tr",
                  p: { a: 0, k: [108.034, 57.867], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: "Transform",
                },
              ],
              nm: "Group 1",
              np: 3,
              cix: 2,
              bm: 0,
              ix: 1,
              mn: "ADBE Vector Group",
              hd: false,
            },
            {
              ty: "gr",
              it: [
                {
                  ind: 0,
                  ty: "sh",
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [12.578, 3.911],
                        [-3.912, 12.578],
                        [-12.578, -3.912],
                        [3.911, -12.579],
                      ],
                      o: [
                        [-12.578, -3.911],
                        [3.911, -12.578],
                        [12.579, 3.911],
                        [-3.911, 12.578],
                      ],
                      v: [
                        [-7.082, 22.775],
                        [-22.774, -7.082],
                        [7.082, -22.774],
                        [22.775, 7.083],
                      ],
                      c: true,
                    },
                    ix: 2,
                  },
                  nm: "Path 1",
                  mn: "ADBE Vector Shape - Group",
                  hd: false,
                },
                {
                  ty: "st",
                  c: {
                    a: 0,
                    k: [0.160784313725, 0.160784313725, 0.152941176471, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 3, ix: 5 },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: "Stroke 1",
                  mn: "ADBE Vector Graphic - Stroke",
                  hd: false,
                },
                {
                  ty: "fl",
                  c: {
                    a: 0,
                    k: [0.733333333333, 0.694117647059, 0.709803921569, 1],
                    ix: 4,
                  },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  bm: 0,
                  nm: "Fill 1",
                  mn: "ADBE Vector Graphic - Fill",
                  hd: false,
                },
                {
                  ty: "tr",
                  p: { a: 0, k: [108.034, 57.867], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: "Transform",
                },
              ],
              nm: "Group 2",
              np: 3,
              cix: 2,
              bm: 0,
              ix: 2,
              mn: "ADBE Vector Group",
              hd: false,
            },
            {
              ty: "gr",
              it: [
                {
                  ind: 0,
                  ty: "sh",
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [7.638, 2.375],
                        [-2.375, 7.638],
                        [-7.638, -2.375],
                        [2.375, -7.638],
                      ],
                      o: [
                        [-7.638, -2.375],
                        [2.375, -7.638],
                        [7.638, 2.375],
                        [-2.375, 7.638],
                      ],
                      v: [
                        [-4.3, 13.829],
                        [-13.829, -4.3],
                        [4.301, -13.829],
                        [13.829, 4.3],
                      ],
                      c: true,
                    },
                    ix: 2,
                  },
                  nm: "Path 1",
                  mn: "ADBE Vector Shape - Group",
                  hd: false,
                },
                {
                  ty: "st",
                  c: {
                    a: 0,
                    k: [0.160784313725, 0.160784313725, 0.152941176471, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 3, ix: 5 },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: "Stroke 1",
                  mn: "ADBE Vector Graphic - Stroke",
                  hd: false,
                },
                {
                  ty: "fl",
                  c: {
                    a: 0,
                    k: [0.552941176471, 0.545098039216, 0.63137254902, 1],
                    ix: 4,
                  },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  bm: 0,
                  nm: "Fill 1",
                  mn: "ADBE Vector Graphic - Fill",
                  hd: false,
                },
                {
                  ty: "tr",
                  p: { a: 0, k: [57.575, 149.559], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: "Transform",
                },
              ],
              nm: "Group 3",
              np: 3,
              cix: 2,
              bm: 0,
              ix: 3,
              mn: "ADBE Vector Group",
              hd: false,
            },
            {
              ty: "gr",
              it: [
                {
                  ind: 0,
                  ty: "sh",
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [12.578, 3.911],
                        [-3.912, 12.578],
                        [-12.578, -3.912],
                        [3.911, -12.579],
                      ],
                      o: [
                        [-12.578, -3.911],
                        [3.911, -12.578],
                        [12.579, 3.911],
                        [-3.912, 12.578],
                      ],
                      v: [
                        [-7.082, 22.775],
                        [-22.774, -7.082],
                        [7.082, -22.774],
                        [22.775, 7.083],
                      ],
                      c: true,
                    },
                    ix: 2,
                  },
                  nm: "Path 1",
                  mn: "ADBE Vector Shape - Group",
                  hd: false,
                },
                {
                  ty: "st",
                  c: {
                    a: 0,
                    k: [0.160784313725, 0.160784313725, 0.152941176471, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 3, ix: 5 },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: "Stroke 1",
                  mn: "ADBE Vector Graphic - Stroke",
                  hd: false,
                },
                {
                  ty: "fl",
                  c: {
                    a: 0,
                    k: [0.733333333333, 0.694117647059, 0.709803921569, 1],
                    ix: 4,
                  },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  bm: 0,
                  nm: "Fill 1",
                  mn: "ADBE Vector Graphic - Fill",
                  hd: false,
                },
                {
                  ty: "tr",
                  p: { a: 0, k: [57.574, 149.558], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: "Transform",
                },
              ],
              nm: "Group 4",
              np: 3,
              cix: 2,
              bm: 0,
              ix: 4,
              mn: "ADBE Vector Group",
              hd: false,
            },
            {
              ty: "gr",
              it: [
                {
                  ind: 0,
                  ty: "sh",
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [-1.162, 3.736],
                        [-0.271, 0.5],
                        [0, 0],
                        [-2.151, 0.64],
                        [-1.973, -1.069],
                        [1.163, -3.739],
                        [0.271, -0.501],
                        [0, 0],
                        [1.231, -0.367],
                        [2.612, 1.415],
                      ],
                      o: [
                        [0.161, -0.518],
                        [0, 0],
                        [1.069, -1.974],
                        [2.15, -0.639],
                        [3.473, 1.882],
                        [-0.16, 0.515],
                        [0, 0],
                        [-1.415, 2.612],
                        [-1.233, 0.365],
                        [-3.472, -1.881],
                      ],
                      v: [
                        [-32.612, 43.089],
                        [-31.961, 41.555],
                        [17.401, -49.564],
                        [22.322, -53.558],
                        [28.625, -52.902],
                        [32.611, -43.203],
                        [31.961, -41.672],
                        [-17.4, 49.445],
                        [-22.324, 53.428],
                        [-28.625, 52.782],
                      ],
                      c: true,
                    },
                    ix: 2,
                  },
                  nm: "Path 1",
                  mn: "ADBE Vector Shape - Group",
                  hd: false,
                },
                {
                  ty: "st",
                  c: {
                    a: 0,
                    k: [0.160784313725, 0.160784313725, 0.152941176471, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 3, ix: 5 },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: "Stroke 1",
                  mn: "ADBE Vector Graphic - Stroke",
                  hd: false,
                },
                {
                  ty: "fl",
                  c: {
                    a: 0,
                    k: [0.733333333333, 0.694117647059, 0.709803921569, 1],
                    ix: 4,
                  },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  bm: 0,
                  nm: "Fill 1",
                  mn: "ADBE Vector Graphic - Fill",
                  hd: false,
                },
                {
                  ty: "tr",
                  p: { a: 0, k: [82.803, 103.775], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: "Transform",
                },
              ],
              nm: "Group 5",
              np: 3,
              cix: 2,
              bm: 0,
              ix: 5,
              mn: "ADBE Vector Group",
              hd: false,
            },
            {
              ty: "gr",
              it: [
                {
                  ind: 0,
                  ty: "sh",
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [0, 0.001],
                        [-0.763, 1.41],
                        [0, 0],
                        [-6.217, 1.848],
                        [-5.702, -3.089],
                        [3.425, -11.014],
                        [0.764, -1.411],
                        [0, 0],
                        [11.772, 6.377],
                        [-3.424, 11.011],
                      ],
                      o: [
                        [0.47, -1.51],
                        [0, 0],
                        [3.088, -5.704],
                        [6.217, -1.847],
                        [10.171, 5.51],
                        [-0.469, 1.508],
                        [0, 0],
                        [-6.377, 11.773],
                        [-10.17, -5.509],
                        [0.001, -0.002],
                      ],
                      v: [
                        [-47.889, 37.093],
                        [-46.031, 32.693],
                        [3.333, -58.427],
                        [17.763, -70.138],
                        [36.247, -68.213],
                        [47.89, -39.695],
                        [46.031, -35.297],
                        [-3.331, 55.823],
                        [-36.247, 65.607],
                        [-47.891, 37.095],
                      ],
                      c: true,
                    },
                    ix: 2,
                  },
                  nm: "Path 1",
                  mn: "ADBE Vector Shape - Group",
                  hd: false,
                },
                {
                  ty: "st",
                  c: {
                    a: 0,
                    k: [0.160784313725, 0.160784313725, 0.152941176471, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 3, ix: 5 },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: "Stroke 1",
                  mn: "ADBE Vector Graphic - Stroke",
                  hd: false,
                },
                {
                  ty: "fl",
                  c: {
                    a: 0,
                    k: [0.552941176471, 0.545098039216, 0.63137254902, 1],
                    ix: 4,
                  },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  bm: 0,
                  nm: "Fill 1",
                  mn: "ADBE Vector Graphic - Fill",
                  hd: false,
                },
                {
                  ty: "tr",
                  p: { a: 0, k: [82.803, 105.017], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: "Transform",
                },
              ],
              nm: "Group 6",
              np: 3,
              cix: 2,
              bm: 0,
              ix: 6,
              mn: "ADBE Vector Group",
              hd: false,
            },
            {
              ty: "gr",
              it: [
                {
                  ind: 0,
                  ty: "sh",
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [0, 0],
                        [21.515, 11.627],
                        [11.627, -21.515],
                        [0, 0],
                        [-21.515, -11.627],
                        [-11.627, 21.515],
                      ],
                      o: [
                        [11.627, -21.515],
                        [-21.515, -11.627],
                        [0, 0],
                        [-11.627, 21.515],
                        [21.516, 11.627],
                        [0, 0],
                      ],
                      v: [
                        [63.591, -24.533],
                        [45.687, -84.542],
                        [-14.322, -66.638],
                        [-63.591, 24.533],
                        [-45.688, 84.542],
                        [14.321, 66.638],
                      ],
                      c: true,
                    },
                    ix: 2,
                  },
                  nm: "Path 1",
                  mn: "ADBE Vector Shape - Group",
                  hd: false,
                },
                {
                  ty: "st",
                  c: {
                    a: 0,
                    k: [0.160784313725, 0.160784313725, 0.152941176471, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 3, ix: 5 },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: "Stroke 1",
                  mn: "ADBE Vector Graphic - Stroke",
                  hd: false,
                },
                {
                  ty: "fl",
                  c: {
                    a: 0,
                    k: [0.733333333333, 0.694117647059, 0.709803921569, 1],
                    ix: 4,
                  },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  bm: 0,
                  nm: "Fill 1",
                  mn: "ADBE Vector Graphic - Fill",
                  hd: false,
                },
                {
                  ty: "tr",
                  p: { a: 0, k: [82.718, 103.669], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: "Transform",
                },
              ],
              nm: "Group 7",
              np: 3,
              cix: 2,
              bm: 0,
              ix: 7,
              mn: "ADBE Vector Group",
              hd: false,
            },
          ],
          ip: 0,
          op: 120,
          st: 0,
          ct: 1,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 7,
          ty: 3,
          nm: "Braço 1 Outlines",
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: {
              a: 1,
              k: [
                {
                  i: { x: [0.833], y: [1] },
                  o: { x: [0.694], y: [0] },
                  t: 0,
                  s: [11.326],
                },
                {
                  i: { x: [0.329], y: [1] },
                  o: { x: [0.694], y: [0] },
                  t: 4.8,
                  s: [-180.674],
                },
                {
                  i: { x: [0.667], y: [1] },
                  o: { x: [0.694], y: [0] },
                  t: 9.6,
                  s: [11.326],
                },
                {
                  i: { x: [0.329], y: [1] },
                  o: { x: [0.694], y: [0] },
                  t: 14.4,
                  s: [-180.674],
                },
                { t: 19.2, s: [11.326] },
              ],
              ix: 10,
            },
            p: {
              a: 1,
              k: [
                {
                  i: { x: 0.441, y: 1 },
                  o: { x: 0.467, y: 0 },
                  t: 4,
                  s: [985.731, 534.02, 0],
                  to: [0, 0, 0],
                  ti: [0, 0, 0],
                },
                {
                  i: { x: 0.667, y: 1 },
                  o: { x: 0.467, y: 0 },
                  t: 8.8,
                  s: [904.731, 527.52, 0],
                  to: [0, 0, 0],
                  ti: [0, 0, 0],
                },
                {
                  i: { x: 0.441, y: 1 },
                  o: { x: 0.467, y: 0 },
                  t: 13.6,
                  s: [985.731, 534.02, 0],
                  to: [0, 0, 0],
                  ti: [0, 0, 0],
                },
                { t: 18.4, s: [904.731, 527.52, 0] },
              ],
              ix: 2,
              l: 2,
            },
            a: { a: 0, k: [152.349, 70.758, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          ip: 0,
          op: 120,
          st: 0,
          ct: 1,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 8,
          ty: 3,
          nm: "Antebraço 1 Outlines",
          parent: 7,
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: {
              a: 1,
              k: [
                {
                  i: { x: [0.833], y: [1] },
                  o: { x: [0.165], y: [0.184] },
                  t: 3.2,
                  s: [-33.308],
                },
                {
                  i: { x: [0.846], y: [1.171] },
                  o: { x: [0.669], y: [0] },
                  t: 5.6,
                  s: [1.854],
                },
                {
                  i: { x: [0.667], y: [1] },
                  o: { x: [0.165], y: [0.184] },
                  t: 8,
                  s: [-33.308],
                },
                {
                  i: { x: [0.667], y: [1] },
                  o: { x: [0.669], y: [0] },
                  t: 10.4,
                  s: [1.854],
                },
                {
                  i: { x: [0.305], y: [1] },
                  o: { x: [0.333], y: [0] },
                  t: 12.8,
                  s: [42.692],
                },
                { t: 15.2, s: [26.854] },
              ],
              ix: 10,
            },
            p: { a: 0, k: [50.68, 50.68, 0], ix: 2, l: 2 },
            a: { a: 0, k: [102.353, 53.084, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          ip: 0,
          op: 120,
          st: 0,
          ct: 1,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 9,
          ty: 3,
          nm: "Mao 1 Outlines",
          parent: 8,
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: {
              a: 1,
              k: [
                {
                  i: { x: [0.833], y: [1] },
                  o: { x: [0.165], y: [1.019] },
                  t: 4,
                  s: [-16.678],
                },
                {
                  i: { x: [0.846], y: [1.949] },
                  o: { x: [0.669], y: [0] },
                  t: 6.4,
                  s: [-22.26],
                },
                {
                  i: { x: [0.667], y: [1] },
                  o: { x: [0.165], y: [1.019] },
                  t: 8.8,
                  s: [-16.678],
                },
                {
                  i: { x: [0.846], y: [1.949] },
                  o: { x: [0.669], y: [0] },
                  t: 11.2,
                  s: [-22.26],
                },
                {
                  i: { x: [0.305], y: [1] },
                  o: { x: [0.165], y: [-0.141] },
                  t: 13.6,
                  s: [-16.678],
                },
                { t: 16, s: [23.74] },
              ],
              ix: 10,
            },
            p: { a: 0, k: [53.083, 144.254, 0], ix: 2, l: 2 },
            a: { a: 0, k: [66.773, 53.487, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          ip: 0,
          op: 120,
          st: 0,
          ct: 1,
          bm: 0,
        },
      ],
    },
  ],
  layer: {
    ddd: 0,
    ind: 2,
    ty: 0,
    nm: "front_arm",
    refId: "comp_1",
    sr: 1,
    ks: {
      o: { a: 0, k: 100, ix: 11 },
      r: { a: 0, k: 0, ix: 10 },
      p: { a: 0, k: [960, 540, 0], ix: 2, l: 2 },
      a: { a: 0, k: [960, 540, 0], ix: 1, l: 2 },
      s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
    },
    ao: 0,
    w: 1920,
    h: 1080,
    ip: 0,
    op: 10,
    st: 0,
    bm: 0,
  },
};
