import type { CharPartJson } from "@/lib/createrandomchar";

export const back_leg2: CharPartJson = {
  asset: [
    {
      id: "comp_7",
      nm: "back_leg",
      fr: 12,
      layers: [
        {
          ddd: 0,
          ind: 1,
          ty: 3,
          nm: "Null 4",
          sr: 1,
          ks: {
            o: { a: 0, k: 0, ix: 11 },
            r: { a: 0, k: 0, ix: 10 },
            p: {
              a: 1,
              k: [
                {
                  i: { x: 0.335, y: 0.335 },
                  o: { x: 0.665, y: 0.665 },
                  t: 0,
                  s: [960, 507.5, 0],
                  to: [0, 0, 0],
                  ti: [0, 0, 0],
                },
                {
                  i: { x: 0.335, y: 0.335 },
                  o: { x: 0.665, y: 0.665 },
                  t: 2,
                  s: [960, 507.5, 0],
                  to: [0, 0, 0],
                  ti: [0, 0, 0],
                },
                {
                  i: { x: 0.335, y: 0.335 },
                  o: { x: 0.665, y: 0.665 },
                  t: 4.8,
                  s: [960, 507.5, 0],
                  to: [0, 0, 0],
                  ti: [0, 0, 0],
                },
                { t: 9.60009765625, s: [960, 507.5, 0] },
              ],
              ix: 2,
              l: 2,
            },
            a: { a: 0, k: [0, 0, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          ip: 0,
          op: 10,
          st: -4,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 2,
          ty: 3,
          nm: "Null 1",
          parent: 1,
          sr: 1,
          ks: {
            o: { a: 0, k: 0, ix: 11 },
            r: { a: 0, k: 0, ix: 10 },
            p: {
              a: 1,
              k: [
                {
                  i: { x: 0.903, y: 1 },
                  o: { x: 0.556, y: 0 },
                  t: 0,
                  s: [0, -29, 0],
                  to: [0, 0, 0],
                  ti: [0, 0, 0],
                },
                {
                  i: { x: 0.667, y: 1 },
                  o: { x: 0.028, y: 0 },
                  t: 2.4,
                  s: [0, 21, 0],
                  to: [0, 0, 0],
                  ti: [0, 0, 0],
                },
                {
                  i: { x: 0.903, y: 1 },
                  o: { x: 0.556, y: 0 },
                  t: 4.8,
                  s: [0, -29, 0],
                  to: [0, 0, 0],
                  ti: [0, 0, 0],
                },
                {
                  i: { x: 0.484, y: 1 },
                  o: { x: 0.028, y: 0 },
                  t: 7.2,
                  s: [0, 21, 0],
                  to: [0, 0, 0],
                  ti: [0, 0, 0],
                },
                { t: 9.60009765625, s: [0, -29, 0] },
              ],
              ix: 2,
              l: 2,
            },
            a: { a: 0, k: [0, 0, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          ip: 0,
          op: 10,
          st: -4,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 3,
          ty: 0,
          nm: "perna 3",
          parent: 2,
          refId: "comp_8",
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: { a: 0, k: 0, ix: 10 },
            p: { a: 0, k: [0, 29, 0], ix: 2, l: 2 },
            a: { a: 0, k: [960, 540, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          w: 1920,
          h: 1080,
          ip: 0,
          op: 10,
          st: -13.7,
          bm: 0,
        },
      ],
    },
    {
      id: "comp_8",
      nm: "perna 3",
      fr: 30,
      layers: [
        {
          ddd: 0,
          ind: 1,
          ty: 4,
          nm: "Coxa 1 Outlines",
          parent: 4,
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: { a: 0, k: -55, ix: 10 },
            p: { a: 0, k: [54.212, 53.127, 0], ix: 2, l: 2 },
            a: { a: 0, k: [109.81, 57.75, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          shapes: [
            {
              ty: "gr",
              it: [
                {
                  ind: 0,
                  ty: "sh",
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [3.684, 5.27],
                        [-5.27, 3.684],
                        [-3.684, -5.27],
                        [5.27, -3.684],
                      ],
                      o: [
                        [-3.684, -5.27],
                        [5.27, -3.684],
                        [3.683, 5.27],
                        [-5.27, 3.683],
                      ],
                      v: [
                        [-9.557, 6.681],
                        [-6.68, -9.557],
                        [9.558, -6.68],
                        [6.681, 9.558],
                      ],
                      c: true,
                    },
                    ix: 2,
                  },
                  nm: "Path 1",
                  mn: "ADBE Vector Shape - Group",
                  hd: false,
                },
                {
                  ty: "st",
                  c: {
                    a: 0,
                    k: [0.160784313725, 0.160784313725, 0.152941176471, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 3, ix: 5 },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: "Stroke 1",
                  mn: "ADBE Vector Graphic - Stroke",
                  hd: false,
                },
                {
                  ty: "fl",
                  c: {
                    a: 0,
                    k: [0.937254961799, 0.921568687289, 0.917647118662, 1],
                    ix: 4,
                  },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  bm: 0,
                  nm: "Fill 1",
                  mn: "ADBE Vector Graphic - Fill",
                  hd: false,
                },
                {
                  ty: "tr",
                  p: { a: 0, k: [109.81, 57.75], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: "Transform",
                },
              ],
              nm: "Group 1",
              np: 3,
              cix: 2,
              bm: 0,
              ix: 1,
              mn: "ADBE Vector Group",
              hd: false,
            },
            {
              ty: "gr",
              it: [
                {
                  ind: 0,
                  ty: "sh",
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [9.805, -6.854],
                        [6.854, 9.805],
                        [-9.805, 6.854],
                        [-6.854, -9.805],
                      ],
                      o: [
                        [-9.805, 6.854],
                        [-6.854, -9.805],
                        [9.805, -6.854],
                        [6.854, 9.805],
                      ],
                      v: [
                        [12.41, 17.753],
                        [-17.754, 12.41],
                        [-12.41, -17.753],
                        [17.754, -12.41],
                      ],
                      c: true,
                    },
                    ix: 2,
                  },
                  nm: "Path 1",
                  mn: "ADBE Vector Shape - Group",
                  hd: false,
                },
                {
                  ty: "st",
                  c: {
                    a: 0,
                    k: [0.160784313725, 0.160784313725, 0.152941176471, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 3, ix: 5 },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: "Stroke 1",
                  mn: "ADBE Vector Graphic - Stroke",
                  hd: false,
                },
                {
                  ty: "fl",
                  c: {
                    a: 0,
                    k: [0.733333333333, 0.694117647059, 0.709803921569, 1],
                    ix: 4,
                  },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  bm: 0,
                  nm: "Fill 1",
                  mn: "ADBE Vector Graphic - Fill",
                  hd: false,
                },
                {
                  ty: "tr",
                  p: { a: 0, k: [109.81, 57.75], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: "Transform",
                },
              ],
              nm: "Group 2",
              np: 3,
              cix: 2,
              bm: 0,
              ix: 2,
              mn: "ADBE Vector Group",
              hd: false,
            },
            {
              ty: "gr",
              it: [
                {
                  ind: 0,
                  ty: "sh",
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [3.684, 5.27],
                        [-5.27, 3.684],
                        [-3.684, -5.27],
                        [5.27, -3.684],
                      ],
                      o: [
                        [-3.684, -5.27],
                        [5.27, -3.684],
                        [3.683, 5.27],
                        [-5.27, 3.683],
                      ],
                      v: [
                        [-9.557, 6.681],
                        [-6.68, -9.557],
                        [9.558, -6.68],
                        [6.681, 9.558],
                      ],
                      c: true,
                    },
                    ix: 2,
                  },
                  nm: "Path 1",
                  mn: "ADBE Vector Shape - Group",
                  hd: false,
                },
                {
                  ty: "st",
                  c: {
                    a: 0,
                    k: [0.160784313725, 0.160784313725, 0.152941176471, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 3, ix: 5 },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: "Stroke 1",
                  mn: "ADBE Vector Graphic - Stroke",
                  hd: false,
                },
                {
                  ty: "fl",
                  c: {
                    a: 0,
                    k: [0.937254961799, 0.921568687289, 0.917647118662, 1],
                    ix: 4,
                  },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  bm: 0,
                  nm: "Fill 1",
                  mn: "ADBE Vector Graphic - Fill",
                  hd: false,
                },
                {
                  ty: "tr",
                  p: { a: 0, k: [92.055, 96.588], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: "Transform",
                },
              ],
              nm: "Group 3",
              np: 3,
              cix: 2,
              bm: 0,
              ix: 3,
              mn: "ADBE Vector Group",
              hd: false,
            },
            {
              ty: "gr",
              it: [
                {
                  ind: 0,
                  ty: "sh",
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [9.805, -6.854],
                        [6.854, 9.805],
                        [-9.805, 6.854],
                        [-6.854, -9.805],
                      ],
                      o: [
                        [-9.805, 6.854],
                        [-6.854, -9.805],
                        [9.805, -6.854],
                        [6.854, 9.805],
                      ],
                      v: [
                        [12.41, 17.753],
                        [-17.754, 12.41],
                        [-12.41, -17.753],
                        [17.754, -12.41],
                      ],
                      c: true,
                    },
                    ix: 2,
                  },
                  nm: "Path 1",
                  mn: "ADBE Vector Shape - Group",
                  hd: false,
                },
                {
                  ty: "st",
                  c: {
                    a: 0,
                    k: [0.160784313725, 0.160784313725, 0.152941176471, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 3, ix: 5 },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: "Stroke 1",
                  mn: "ADBE Vector Graphic - Stroke",
                  hd: false,
                },
                {
                  ty: "fl",
                  c: {
                    a: 0,
                    k: [0.733333333333, 0.694117647059, 0.709803921569, 1],
                    ix: 4,
                  },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  bm: 0,
                  nm: "Fill 1",
                  mn: "ADBE Vector Graphic - Fill",
                  hd: false,
                },
                {
                  ty: "tr",
                  p: { a: 0, k: [92.055, 96.588], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: "Transform",
                },
              ],
              nm: "Group 4",
              np: 3,
              cix: 2,
              bm: 0,
              ix: 4,
              mn: "ADBE Vector Group",
              hd: false,
            },
            {
              ty: "gr",
              it: [
                {
                  ind: 0,
                  ty: "sh",
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [3.684, 5.27],
                        [-5.269, 3.683],
                        [-3.684, -5.27],
                        [5.27, -3.684],
                      ],
                      o: [
                        [-3.684, -5.27],
                        [5.27, -3.684],
                        [3.683, 5.27],
                        [-5.27, 3.684],
                      ],
                      v: [
                        [-9.557, 6.68],
                        [-6.681, -9.557],
                        [9.558, -6.681],
                        [6.68, 9.557],
                      ],
                      c: true,
                    },
                    ix: 2,
                  },
                  nm: "Path 1",
                  mn: "ADBE Vector Shape - Group",
                  hd: false,
                },
                {
                  ty: "st",
                  c: {
                    a: 0,
                    k: [0.160784313725, 0.160784313725, 0.152941176471, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 3, ix: 5 },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: "Stroke 1",
                  mn: "ADBE Vector Graphic - Stroke",
                  hd: false,
                },
                {
                  ty: "fl",
                  c: {
                    a: 0,
                    k: [0.937254961799, 0.921568687289, 0.917647118662, 1],
                    ix: 4,
                  },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  bm: 0,
                  nm: "Fill 1",
                  mn: "ADBE Vector Graphic - Fill",
                  hd: false,
                },
                {
                  ty: "tr",
                  p: { a: 0, k: [76.088, 137.31], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: "Transform",
                },
              ],
              nm: "Group 5",
              np: 3,
              cix: 2,
              bm: 0,
              ix: 5,
              mn: "ADBE Vector Group",
              hd: false,
            },
            {
              ty: "gr",
              it: [
                {
                  ind: 0,
                  ty: "sh",
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [9.805, -6.854],
                        [6.854, 9.805],
                        [-9.805, 6.854],
                        [-6.854, -9.805],
                      ],
                      o: [
                        [-9.805, 6.854],
                        [-6.854, -9.805],
                        [9.805, -6.854],
                        [6.854, 9.805],
                      ],
                      v: [
                        [12.41, 17.753],
                        [-17.754, 12.41],
                        [-12.41, -17.753],
                        [17.754, -12.41],
                      ],
                      c: true,
                    },
                    ix: 2,
                  },
                  nm: "Path 1",
                  mn: "ADBE Vector Shape - Group",
                  hd: false,
                },
                {
                  ty: "st",
                  c: {
                    a: 0,
                    k: [0.160784313725, 0.160784313725, 0.152941176471, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 3, ix: 5 },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: "Stroke 1",
                  mn: "ADBE Vector Graphic - Stroke",
                  hd: false,
                },
                {
                  ty: "fl",
                  c: {
                    a: 0,
                    k: [0.733333333333, 0.694117647059, 0.709803921569, 1],
                    ix: 4,
                  },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  bm: 0,
                  nm: "Fill 1",
                  mn: "ADBE Vector Graphic - Fill",
                  hd: false,
                },
                {
                  ty: "tr",
                  p: { a: 0, k: [76.089, 137.309], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: "Transform",
                },
              ],
              nm: "Group 6",
              np: 3,
              cix: 2,
              bm: 0,
              ix: 6,
              mn: "ADBE Vector Group",
              hd: false,
            },
            {
              ty: "gr",
              it: [
                {
                  ind: 0,
                  ty: "sh",
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [3.684, 5.27],
                        [-5.269, 3.683],
                        [-3.684, -5.27],
                        [5.27, -3.684],
                      ],
                      o: [
                        [-3.684, -5.27],
                        [5.27, -3.684],
                        [3.683, 5.27],
                        [-5.27, 3.684],
                      ],
                      v: [
                        [-9.557, 6.68],
                        [-6.681, -9.557],
                        [9.558, -6.681],
                        [6.68, 9.557],
                      ],
                      c: true,
                    },
                    ix: 2,
                  },
                  nm: "Path 1",
                  mn: "ADBE Vector Shape - Group",
                  hd: false,
                },
                {
                  ty: "st",
                  c: {
                    a: 0,
                    k: [0.160784313725, 0.160784313725, 0.152941176471, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 3, ix: 5 },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: "Stroke 1",
                  mn: "ADBE Vector Graphic - Stroke",
                  hd: false,
                },
                {
                  ty: "fl",
                  c: {
                    a: 0,
                    k: [0.937254961799, 0.921568687289, 0.917647118662, 1],
                    ix: 4,
                  },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  bm: 0,
                  nm: "Fill 1",
                  mn: "ADBE Vector Graphic - Fill",
                  hd: false,
                },
                {
                  ty: "tr",
                  p: { a: 0, k: [60.314, 177.58], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: "Transform",
                },
              ],
              nm: "Group 7",
              np: 3,
              cix: 2,
              bm: 0,
              ix: 7,
              mn: "ADBE Vector Group",
              hd: false,
            },
            {
              ty: "gr",
              it: [
                {
                  ind: 0,
                  ty: "sh",
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [9.805, -6.854],
                        [6.854, 9.805],
                        [-9.805, 6.854],
                        [-6.854, -9.805],
                      ],
                      o: [
                        [-9.805, 6.854],
                        [-6.854, -9.805],
                        [9.805, -6.854],
                        [6.854, 9.805],
                      ],
                      v: [
                        [12.41, 17.753],
                        [-17.754, 12.41],
                        [-12.41, -17.753],
                        [17.754, -12.41],
                      ],
                      c: true,
                    },
                    ix: 2,
                  },
                  nm: "Path 1",
                  mn: "ADBE Vector Shape - Group",
                  hd: false,
                },
                {
                  ty: "st",
                  c: {
                    a: 0,
                    k: [0.160784313725, 0.160784313725, 0.152941176471, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 3, ix: 5 },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: "Stroke 1",
                  mn: "ADBE Vector Graphic - Stroke",
                  hd: false,
                },
                {
                  ty: "fl",
                  c: {
                    a: 0,
                    k: [0.733333333333, 0.694117647059, 0.709803921569, 1],
                    ix: 4,
                  },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  bm: 0,
                  nm: "Fill 1",
                  mn: "ADBE Vector Graphic - Fill",
                  hd: false,
                },
                {
                  ty: "tr",
                  p: { a: 0, k: [60.314, 177.579], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: "Transform",
                },
              ],
              nm: "Group 8",
              np: 3,
              cix: 2,
              bm: 0,
              ix: 8,
              mn: "ADBE Vector Group",
              hd: false,
            },
            {
              ty: "gr",
              it: [
                {
                  ind: 0,
                  ty: "sh",
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [0, 0],
                        [-23.287, -9.744],
                        [-9.744, 23.287],
                        [0, 0],
                        [23.287, 9.744],
                        [9.744, -23.287],
                      ],
                      o: [
                        [-9.744, 23.287],
                        [23.287, 9.744],
                        [0, 0],
                        [9.744, -23.288],
                        [-23.287, -9.744],
                        [0, 0],
                      ],
                      v: [
                        [-67.18, 42.14],
                        [-42.658, 101.949],
                        [17.15, 77.426],
                        [67.18, -42.14],
                        [42.658, -101.949],
                        [-17.15, -77.426],
                      ],
                      c: true,
                    },
                    ix: 2,
                  },
                  nm: "Path 1",
                  mn: "ADBE Vector Shape - Group",
                  hd: false,
                },
                {
                  ty: "st",
                  c: {
                    a: 0,
                    k: [0.160784313725, 0.160784313725, 0.152941176471, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 3, ix: 5 },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: "Stroke 1",
                  mn: "ADBE Vector Graphic - Stroke",
                  hd: false,
                },
                {
                  ty: "fl",
                  c: {
                    a: 0,
                    k: [0.552941176471, 0.545098039216, 0.63137254902, 1],
                    ix: 4,
                  },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  bm: 0,
                  nm: "Fill 1",
                  mn: "ADBE Vector Graphic - Fill",
                  hd: false,
                },
                {
                  ty: "tr",
                  p: { a: 0, k: [84.424, 119.192], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: "Transform",
                },
              ],
              nm: "Group 9",
              np: 3,
              cix: 2,
              bm: 0,
              ix: 9,
              mn: "ADBE Vector Group",
              hd: false,
            },
          ],
          ip: 0,
          op: 120,
          st: 0,
          ct: 1,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 2,
          ty: 4,
          nm: "Canela 1 Outlines",
          parent: 5,
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: { a: 0, k: -148.189, ix: 10 },
            p: { a: 0, k: [54.621, 54.621, 0], ix: 2, l: 2 },
            a: { a: 0, k: [137.794, 83.275, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          shapes: [
            {
              ty: "gr",
              it: [
                {
                  ind: 0,
                  ty: "sh",
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [0, 0],
                        [0, 0],
                      ],
                      o: [
                        [0, 0],
                        [0, 0],
                      ],
                      v: [
                        [6.557, -18.689],
                        [-6.557, 18.689],
                      ],
                      c: false,
                    },
                    ix: 2,
                  },
                  nm: "Path 1",
                  mn: "ADBE Vector Shape - Group",
                  hd: false,
                },
                {
                  ty: "st",
                  c: {
                    a: 0,
                    k: [0.160784313725, 0.160784313725, 0.152941176471, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 3, ix: 5 },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: "Stroke 1",
                  mn: "ADBE Vector Graphic - Stroke",
                  hd: false,
                },
                {
                  ty: "fl",
                  c: {
                    a: 0,
                    k: [0.960784373564, 0.647058823529, 0.537254901961, 1],
                    ix: 4,
                  },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  bm: 0,
                  nm: "Fill 1",
                  mn: "ADBE Vector Graphic - Fill",
                  hd: false,
                },
                {
                  ty: "tr",
                  p: { a: 0, k: [106.338, 68.985], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: "Transform",
                },
              ],
              nm: "Group 1",
              np: 3,
              cix: 2,
              bm: 0,
              ix: 1,
              mn: "ADBE Vector Group",
              hd: false,
            },
            {
              ty: "gr",
              it: [
                {
                  ind: 0,
                  ty: "sh",
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [0, 0],
                        [0, 0],
                      ],
                      o: [
                        [0, 0],
                        [0, 0],
                      ],
                      v: [
                        [-9.132, 17.485],
                        [9.132, -17.485],
                      ],
                      c: false,
                    },
                    ix: 2,
                  },
                  nm: "Path 1",
                  mn: "ADBE Vector Shape - Group",
                  hd: false,
                },
                {
                  ty: "st",
                  c: {
                    a: 0,
                    k: [0.160784313725, 0.160784313725, 0.152941176471, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 3, ix: 5 },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: "Stroke 1",
                  mn: "ADBE Vector Graphic - Stroke",
                  hd: false,
                },
                {
                  ty: "fl",
                  c: {
                    a: 0,
                    k: [0.960784373564, 0.647058823529, 0.537254901961, 1],
                    ix: 4,
                  },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  bm: 0,
                  nm: "Fill 1",
                  mn: "ADBE Vector Graphic - Fill",
                  hd: false,
                },
                {
                  ty: "tr",
                  p: { a: 0, k: [88.161, 60.49], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: "Transform",
                },
              ],
              nm: "Group 2",
              np: 3,
              cix: 2,
              bm: 0,
              ix: 2,
              mn: "ADBE Vector Group",
              hd: false,
            },
            {
              ty: "gr",
              it: [
                {
                  ind: 0,
                  ty: "sh",
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [0, 0],
                        [0, 0],
                      ],
                      o: [
                        [0, 0],
                        [0, 0],
                      ],
                      v: [
                        [-9.932, 17.15],
                        [9.932, -17.15],
                      ],
                      c: false,
                    },
                    ix: 2,
                  },
                  nm: "Path 1",
                  mn: "ADBE Vector Shape - Group",
                  hd: false,
                },
                {
                  ty: "st",
                  c: {
                    a: 0,
                    k: [0.160784313725, 0.160784313725, 0.152941176471, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 3, ix: 5 },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: "Stroke 1",
                  mn: "ADBE Vector Graphic - Stroke",
                  hd: false,
                },
                {
                  ty: "fl",
                  c: {
                    a: 0,
                    k: [0.960784373564, 0.647058823529, 0.537254901961, 1],
                    ix: 4,
                  },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  bm: 0,
                  nm: "Fill 1",
                  mn: "ADBE Vector Graphic - Fill",
                  hd: false,
                },
                {
                  ty: "tr",
                  p: { a: 0, k: [70.524, 52.286], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: "Transform",
                },
              ],
              nm: "Group 3",
              np: 3,
              cix: 2,
              bm: 0,
              ix: 3,
              mn: "ADBE Vector Group",
              hd: false,
            },
            {
              ty: "gr",
              it: [
                {
                  ind: 0,
                  ty: "sh",
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [0, 0],
                        [0, 0],
                        [2.396, 6.72],
                        [-3.057, 6.445],
                        [-4.252, 2.686],
                        [-8.32, -3.945],
                        [0, 0],
                      ],
                      o: [
                        [0, 0],
                        [-6.445, -3.058],
                        [-2.395, -6.719],
                        [2.175, -4.585],
                        [7.806, -4.93],
                        [0, 0],
                        [0, 0],
                      ],
                      v: [
                        [5.576, 30.968],
                        [-14.936, 21.238],
                        [-28.647, 6.076],
                        [-27.621, -14.338],
                        [-17.796, -25.452],
                        [7.957, -27.023],
                        [31.041, -16.072],
                      ],
                      c: true,
                    },
                    ix: 2,
                  },
                  nm: "Path 1",
                  mn: "ADBE Vector Shape - Group",
                  hd: false,
                },
                {
                  ty: "st",
                  c: {
                    a: 0,
                    k: [0.160784313725, 0.160784313725, 0.152941176471, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 3, ix: 5 },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: "Stroke 1",
                  mn: "ADBE Vector Graphic - Stroke",
                  hd: false,
                },
                {
                  ty: "fl",
                  c: {
                    a: 0,
                    k: [0.552941176471, 0.545098039216, 0.63137254902, 1],
                    ix: 4,
                  },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  bm: 0,
                  nm: "Fill 1",
                  mn: "ADBE Vector Graphic - Fill",
                  hd: false,
                },
                {
                  ty: "tr",
                  p: { a: 0, k: [38.541, 38.468], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: "Transform",
                },
              ],
              nm: "Group 4",
              np: 3,
              cix: 2,
              bm: 0,
              ix: 4,
              mn: "ADBE Vector Group",
              hd: false,
            },
            {
              ty: "gr",
              it: [
                {
                  ind: 0,
                  ty: "sh",
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [5.078, -3.549],
                        [3.549, 5.077],
                        [-5.077, 3.549],
                        [-3.549, -5.078],
                      ],
                      o: [
                        [-5.078, 3.549],
                        [-3.549, -5.078],
                        [5.078, -3.55],
                        [3.55, 5.078],
                      ],
                      v: [
                        [6.426, 9.194],
                        [-9.194, 6.427],
                        [-6.427, -9.193],
                        [9.193, -6.426],
                      ],
                      c: true,
                    },
                    ix: 2,
                  },
                  nm: "Path 1",
                  mn: "ADBE Vector Shape - Group",
                  hd: false,
                },
                {
                  ty: "st",
                  c: {
                    a: 0,
                    k: [0.160784313725, 0.160784313725, 0.152941176471, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 3, ix: 5 },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: "Stroke 1",
                  mn: "ADBE Vector Graphic - Stroke",
                  hd: false,
                },
                {
                  ty: "fl",
                  c: {
                    a: 0,
                    k: [0.937254961799, 0.921568687289, 0.917647118662, 1],
                    ix: 4,
                  },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  bm: 0,
                  nm: "Fill 1",
                  mn: "ADBE Vector Graphic - Fill",
                  hd: false,
                },
                {
                  ty: "tr",
                  p: { a: 0, k: [137.794, 83.274], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: "Transform",
                },
              ],
              nm: "Group 5",
              np: 3,
              cix: 2,
              bm: 0,
              ix: 5,
              mn: "ADBE Vector Group",
              hd: false,
            },
            {
              ty: "gr",
              it: [
                {
                  ind: 0,
                  ty: "sh",
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [12.263, -8.572],
                        [8.572, 12.262],
                        [-12.263, 8.571],
                        [-8.571, -12.263],
                      ],
                      o: [
                        [-12.263, 8.572],
                        [-8.572, -12.263],
                        [12.262, -8.572],
                        [8.572, 12.263],
                      ],
                      v: [
                        [15.521, 22.203],
                        [-22.203, 15.52],
                        [-15.52, -22.204],
                        [22.204, -15.521],
                      ],
                      c: true,
                    },
                    ix: 2,
                  },
                  nm: "Path 1",
                  mn: "ADBE Vector Shape - Group",
                  hd: false,
                },
                {
                  ty: "st",
                  c: {
                    a: 0,
                    k: [0.160784313725, 0.160784313725, 0.152941176471, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 3, ix: 5 },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: "Stroke 1",
                  mn: "ADBE Vector Graphic - Stroke",
                  hd: false,
                },
                {
                  ty: "fl",
                  c: {
                    a: 0,
                    k: [0.733333333333, 0.694117647059, 0.709803921569, 1],
                    ix: 4,
                  },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  bm: 0,
                  nm: "Fill 1",
                  mn: "ADBE Vector Graphic - Fill",
                  hd: false,
                },
                {
                  ty: "tr",
                  p: { a: 0, k: [137.794, 83.275], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: "Transform",
                },
              ],
              nm: "Group 6",
              np: 3,
              cix: 2,
              bm: 0,
              ix: 6,
              mn: "ADBE Vector Group",
              hd: false,
            },
            {
              ty: "gr",
              it: [
                {
                  ind: 0,
                  ty: "sh",
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [-0.001, 0.001],
                        [-6.14, -2.912],
                        [0, 0],
                        [-1.768, -4.958],
                        [2.256, -4.756],
                        [3.132, -1.978],
                        [6.14, 2.913],
                        [0, 0],
                        [1.767, 4.958],
                        [-2.256, 4.757],
                        [-3.129, 1.977],
                      ],
                      o: [
                        [5.765, -3.641],
                        [0, 0],
                        [4.756, 2.256],
                        [1.767, 4.959],
                        [-1.606, 3.385],
                        [-5.763, 3.641],
                        [0, 0],
                        [-4.756, -2.256],
                        [-1.768, -4.958],
                        [1.606, -3.384],
                        [0.001, 0],
                      ],
                      v: [
                        [-60.681, -40.064],
                        [-41.668, -41.227],
                        [58.561, 5.615],
                        [68.678, 16.802],
                        [67.92, 31.866],
                        [60.679, 40.064],
                        [41.668, 41.226],
                        [-58.561, -5.616],
                        [-68.677, -16.804],
                        [-67.92, -31.868],
                        [-60.683, -40.063],
                      ],
                      c: true,
                    },
                    ix: 2,
                  },
                  nm: "Path 1",
                  mn: "ADBE Vector Shape - Group",
                  hd: false,
                },
                {
                  ty: "st",
                  c: {
                    a: 0,
                    k: [0.160784313725, 0.160784313725, 0.152941176471, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 3, ix: 5 },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: "Stroke 1",
                  mn: "ADBE Vector Graphic - Stroke",
                  hd: false,
                },
                {
                  ty: "fl",
                  c: {
                    a: 0,
                    k: [0.733333333333, 0.694117647059, 0.709803921569, 1],
                    ix: 4,
                  },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  bm: 0,
                  nm: "Fill 1",
                  mn: "ADBE Vector Graphic - Fill",
                  hd: false,
                },
                {
                  ty: "tr",
                  p: { a: 0, k: [88.079, 60.452], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: "Transform",
                },
              ],
              nm: "Group 7",
              np: 3,
              cix: 2,
              bm: 0,
              ix: 7,
              mn: "ADBE Vector Group",
              hd: false,
            },
          ],
          ip: 0,
          op: 120,
          st: 0,
          ct: 1,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 3,
          ty: 4,
          nm: "Sapato 1 Outlines",
          parent: 6,
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: { a: 0, k: 204.311, ix: 10 },
            p: { a: 0, k: [46.578, 33.101, 0], ix: 2, l: 2 },
            a: { a: 0, k: [124.389, 90.061, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          shapes: [
            {
              ty: "gr",
              it: [
                {
                  ind: 0,
                  ty: "sh",
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [2.008, -2.764],
                        [0, 0],
                        [2.748, 1.963],
                        [-1.975, 2.764],
                        [0, 0],
                        [-2.764, -1.975],
                        [0, 0],
                      ],
                      o: [
                        [0, 0],
                        [-1.985, 2.732],
                        [-2.764, -1.974],
                        [0, 0],
                        [1.974, -2.763],
                        [0, 0],
                        [2.779, 1.986],
                      ],
                      v: [
                        [43.109, -48.552],
                        [-33.163, 56.409],
                        [-41.712, 57.798],
                        [-43.142, 49.219],
                        [32.269, -56.357],
                        [40.848, -57.786],
                        [41.709, -57.172],
                      ],
                      c: true,
                    },
                    ix: 2,
                  },
                  nm: "Path 1",
                  mn: "ADBE Vector Shape - Group",
                  hd: false,
                },
                {
                  ty: "st",
                  c: {
                    a: 0,
                    k: [0.160784313725, 0.160784313725, 0.152941176471, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 3, ix: 5 },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: "Stroke 1",
                  mn: "ADBE Vector Graphic - Stroke",
                  hd: false,
                },
                {
                  ty: "fl",
                  c: {
                    a: 0,
                    k: [0.552941176471, 0.545098039216, 0.63137254902, 1],
                    ix: 4,
                  },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  bm: 0,
                  nm: "Fill 1",
                  mn: "ADBE Vector Graphic - Fill",
                  hd: false,
                },
                {
                  ty: "tr",
                  p: { a: 0, k: [66.169, 80.813], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: "Transform",
                },
              ],
              nm: "Group 1",
              np: 3,
              cix: 2,
              bm: 0,
              ix: 1,
              mn: "ADBE Vector Group",
              hd: false,
            },
            {
              ty: "gr",
              it: [
                {
                  ind: 0,
                  ty: "sh",
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [-3.45, -2.464],
                        [0, 0],
                        [2.507, -3.45],
                        [0, 0],
                        [3.43, 2.45],
                        [0, 0],
                        [-2.464, 3.45],
                        [0, 0],
                      ],
                      o: [
                        [0, 0],
                        [3.47, 2.478],
                        [0, 0],
                        [-2.477, 3.41],
                        [0, 0],
                        [-3.45, -2.464],
                        [0, 0],
                        [2.464, -3.45],
                      ],
                      v: [
                        [39.736, -70.828],
                        [54.443, -60.323],
                        [56.191, -49.564],
                        [-30.043, 69.108],
                        [-40.714, 70.842],
                        [-54.449, 61.031],
                        [-56.234, 50.323],
                        [29.028, -69.043],
                      ],
                      c: true,
                    },
                    ix: 2,
                  },
                  nm: "Path 1",
                  mn: "ADBE Vector Shape - Group",
                  hd: false,
                },
                {
                  ty: "st",
                  c: {
                    a: 0,
                    k: [0.160784313725, 0.160784313725, 0.152941176471, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 3, ix: 5 },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: "Stroke 1",
                  mn: "ADBE Vector Graphic - Stroke",
                  hd: false,
                },
                {
                  ty: "fl",
                  c: {
                    a: 0,
                    k: [0.733333333333, 0.694117647059, 0.709803921569, 1],
                    ix: 4,
                  },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  bm: 0,
                  nm: "Fill 1",
                  mn: "ADBE Vector Graphic - Fill",
                  hd: false,
                },
                {
                  ty: "tr",
                  p: { a: 0, k: [66.198, 80.792], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: "Transform",
                },
              ],
              nm: "Group 2",
              np: 3,
              cix: 2,
              bm: 0,
              ix: 2,
              mn: "ADBE Vector Group",
              hd: false,
            },
            {
              ty: "gr",
              it: [
                {
                  ind: 0,
                  ty: "sh",
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [0, 0],
                        [0, 0],
                        [16.439, 6.153],
                        [0.438, 0.187],
                        [0, 0],
                      ],
                      o: [
                        [0, 0],
                        [0.613, 17.542],
                        [-0.442, -0.166],
                        [0, 0],
                        [0, 0],
                      ],
                      v: [
                        [20.753, -35.829],
                        [22.186, 5.219],
                        [-10.977, 29.675],
                        [-12.296, 29.146],
                        [-22.799, 24.107],
                      ],
                      c: true,
                    },
                    ix: 2,
                  },
                  nm: "Path 1",
                  mn: "ADBE Vector Shape - Group",
                  hd: false,
                },
                {
                  ty: "st",
                  c: {
                    a: 0,
                    k: [0.160784313725, 0.160784313725, 0.152941176471, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 3, ix: 5 },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: "Stroke 1",
                  mn: "ADBE Vector Graphic - Stroke",
                  hd: false,
                },
                {
                  ty: "fl",
                  c: {
                    a: 0,
                    k: [0.733333333333, 0.694117647059, 0.709803921569, 1],
                    ix: 4,
                  },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  bm: 0,
                  nm: "Fill 1",
                  mn: "ADBE Vector Graphic - Fill",
                  hd: false,
                },
                {
                  ty: "tr",
                  p: { a: 0, k: [58.954, 125.794], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: "Transform",
                },
              ],
              nm: "Group 3",
              np: 3,
              cix: 2,
              bm: 0,
              ix: 3,
              mn: "ADBE Vector Group",
              hd: false,
            },
            {
              ty: "gr",
              it: [
                {
                  ind: 0,
                  ty: "sh",
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [0, 0],
                        [0, 0],
                        [0, 0],
                        [0, 0],
                        [0, 0],
                      ],
                      o: [
                        [0, 0],
                        [0, 0],
                        [0, 0],
                        [0, 0],
                        [0, 0],
                      ],
                      v: [
                        [21.583, 37.337],
                        [-37.542, 66.721],
                        [-66.849, 52.594],
                        [18.376, -66.721],
                        [66.849, -32.097],
                      ],
                      c: true,
                    },
                    ix: 2,
                  },
                  nm: "Path 1",
                  mn: "ADBE Vector Shape - Group",
                  hd: false,
                },
                {
                  ty: "st",
                  c: {
                    a: 0,
                    k: [0.160784313725, 0.160784313725, 0.152941176471, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 3, ix: 5 },
                  lc: 2,
                  lj: 2,
                  bm: 0,
                  nm: "Stroke 1",
                  mn: "ADBE Vector Graphic - Stroke",
                  hd: false,
                },
                {
                  ty: "fl",
                  c: {
                    a: 0,
                    k: [0.937254961799, 0.921568687289, 0.917647118662, 1],
                    ix: 4,
                  },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  bm: 0,
                  nm: "Fill 1",
                  mn: "ADBE Vector Graphic - Fill",
                  hd: false,
                },
                {
                  ty: "tr",
                  p: { a: 0, k: [83.428, 82.686], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: "Transform",
                },
              ],
              nm: "Group 4",
              np: 3,
              cix: 2,
              bm: 0,
              ix: 4,
              mn: "ADBE Vector Group",
              hd: false,
            },
          ],
          ip: 0,
          op: 120,
          st: 0,
          ct: 1,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 4,
          ty: 3,
          nm: "Coxa 2 Outlines 3",
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: {
              a: 1,
              k: [
                {
                  i: { x: [0.515], y: [0.322] },
                  o: { x: [0.459], y: [0] },
                  t: 9.2,
                  s: [76.189],
                },
                {
                  i: { x: [0.527], y: [1] },
                  o: { x: [0.22], y: [0.237] },
                  t: 10.4,
                  s: [22.625],
                },
                {
                  i: { x: [0.667], y: [1] },
                  o: { x: [0.333], y: [0] },
                  t: 11.6,
                  s: [-46.811],
                },
                {
                  i: { x: [0.667], y: [-0.193] },
                  o: { x: [0.333], y: [0] },
                  t: 14,
                  s: [-10.311],
                },
                {
                  i: { x: [0.667], y: [0.839] },
                  o: { x: [0.333], y: [0.115] },
                  t: 15.2,
                  s: [1.962],
                },
                {
                  i: { x: [0.667], y: [1] },
                  o: { x: [0.333], y: [3.636] },
                  t: 15.6,
                  s: [44.464],
                },
                {
                  i: { x: [0.667], y: [0.919] },
                  o: { x: [0.333], y: [0] },
                  t: 16.4,
                  s: [48.235],
                },
                {
                  i: { x: [0.667], y: [1] },
                  o: { x: [0.333], y: [0.545] },
                  t: 16.8,
                  s: [64.305],
                },
                {
                  i: { x: [0.515], y: [0.322] },
                  o: { x: [0.459], y: [0] },
                  t: 18.8,
                  s: [76.189],
                },
                {
                  i: { x: [0.527], y: [1] },
                  o: { x: [0.22], y: [0.237] },
                  t: 20,
                  s: [22.625],
                },
                {
                  i: { x: [0.667], y: [1] },
                  o: { x: [0.333], y: [0] },
                  t: 21.2,
                  s: [-46.811],
                },
                {
                  i: { x: [0.667], y: [-0.193] },
                  o: { x: [0.333], y: [0] },
                  t: 23.6,
                  s: [-10.311],
                },
                {
                  i: { x: [0.667], y: [0.839] },
                  o: { x: [0.333], y: [0.115] },
                  t: 24.8,
                  s: [1.962],
                },
                {
                  i: { x: [0.667], y: [1] },
                  o: { x: [0.333], y: [3.636] },
                  t: 25.2,
                  s: [44.464],
                },
                {
                  i: { x: [0.667], y: [0.919] },
                  o: { x: [0.333], y: [0] },
                  t: 26,
                  s: [48.235],
                },
                {
                  i: { x: [0.667], y: [1] },
                  o: { x: [0.333], y: [0.545] },
                  t: 26.4,
                  s: [64.305],
                },
                { t: 28.4, s: [76.189] },
              ],
              ix: 10,
            },
            p: {
              a: 1,
              k: [
                {
                  i: { x: 0.667, y: 1 },
                  o: { x: 0.333, y: 0 },
                  t: 9.2,
                  s: [892.838, 631.863, 0],
                  to: [-6.838, -4.363, 0],
                  ti: [4.713, -1.762, 0],
                },
                {
                  i: { x: 0.667, y: 1 },
                  o: { x: 0.333, y: 0 },
                  t: 14,
                  s: [962.838, 647.863, 0],
                  to: [-4.713, 1.762, 0],
                  ti: [6.838, 4.363, 0],
                },
                {
                  i: { x: 0.667, y: 1 },
                  o: { x: 0.333, y: 0 },
                  t: 18.8,
                  s: [892.838, 631.863, 0],
                  to: [-6.838, -4.363, 0],
                  ti: [4.713, -1.762, 0],
                },
                {
                  i: { x: 0.667, y: 1 },
                  o: { x: 0.333, y: 0 },
                  t: 23.6,
                  s: [962.838, 647.863, 0],
                  to: [-4.713, 1.762, 0],
                  ti: [6.838, 4.363, 0],
                },
                { t: 28.4, s: [892.838, 631.863, 0] },
              ],
              ix: 2,
              l: 2,
            },
            a: { a: 0, k: [54.622, 54.621, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          ip: 0,
          op: 120,
          st: 0,
          ct: 1,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 5,
          ty: 3,
          nm: "Canela 2 Outlines 3",
          parent: 4,
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: {
              a: 1,
              k: [
                {
                  i: { x: [0], y: [1.052] },
                  o: { x: [0.333], y: [0] },
                  t: 9.2,
                  s: [82],
                },
                {
                  i: { x: [0.667], y: [0.77] },
                  o: { x: [0.333], y: [0] },
                  t: 10.8,
                  s: [128.046],
                },
                {
                  i: { x: [0.667], y: [1] },
                  o: { x: [0.333], y: [1.214] },
                  t: 12.8,
                  s: [18.456],
                },
                {
                  i: { x: [0.667], y: [0.853] },
                  o: { x: [0.333], y: [0] },
                  t: 14,
                  s: [6],
                },
                {
                  i: { x: [0.667], y: [1.001] },
                  o: { x: [0.333], y: [0.025] },
                  t: 14.8,
                  s: [18.968],
                },
                {
                  i: { x: [0.667], y: [0.899] },
                  o: { x: [0.333], y: [0.001] },
                  t: 15.2,
                  s: [57.108],
                },
                {
                  i: { x: [0.667], y: [0.804] },
                  o: { x: [0.333], y: [-0.489] },
                  t: 15.6,
                  s: [0.973],
                },
                {
                  i: { x: [0.667], y: [1] },
                  o: { x: [0.333], y: [-0.111] },
                  t: 16.4,
                  s: [24.084],
                },
                {
                  i: { x: [0.454], y: [1] },
                  o: { x: [0.067], y: [-0.002] },
                  t: 16.8,
                  s: [3.666],
                },
                {
                  i: { x: [0.667], y: [1] },
                  o: { x: [0.333], y: [0] },
                  t: 18,
                  s: [51.37],
                },
                {
                  i: { x: [0], y: [1.052] },
                  o: { x: [0.333], y: [0] },
                  t: 18.8,
                  s: [82],
                },
                {
                  i: { x: [0.667], y: [0.77] },
                  o: { x: [0.333], y: [0] },
                  t: 20.4,
                  s: [128.046],
                },
                {
                  i: { x: [0.667], y: [1] },
                  o: { x: [0.333], y: [-1.039] },
                  t: 22.4,
                  s: [18.456],
                },
                {
                  i: { x: [0.667], y: [1.136] },
                  o: { x: [0.333], y: [0] },
                  t: 23.6,
                  s: [33],
                },
                {
                  i: { x: [0.667], y: [1.001] },
                  o: { x: [0.333], y: [0.025] },
                  t: 24.4,
                  s: [18.968],
                },
                {
                  i: { x: [0.667], y: [0.899] },
                  o: { x: [0.333], y: [0.001] },
                  t: 24.8,
                  s: [57.108],
                },
                {
                  i: { x: [0.667], y: [0.804] },
                  o: { x: [0.333], y: [-0.489] },
                  t: 25.2,
                  s: [0.973],
                },
                {
                  i: { x: [0.667], y: [1] },
                  o: { x: [0.333], y: [-0.111] },
                  t: 26,
                  s: [24.084],
                },
                {
                  i: { x: [0.454], y: [1] },
                  o: { x: [0.067], y: [-0.002] },
                  t: 26.4,
                  s: [3.666],
                },
                {
                  i: { x: [0.667], y: [1] },
                  o: { x: [0.333], y: [0] },
                  t: 27.6,
                  s: [51.37],
                },
                { t: 28.4, s: [82] },
              ],
              ix: 10,
            },
            p: { a: 0, k: [123.959, 164.128, 0], ix: 2, l: 2 },
            a: { a: 0, k: [54.621, 54.621, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          ip: 0,
          op: 120,
          st: 0,
          ct: 1,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 6,
          ty: 3,
          nm: "Sapato 2 Outlines 3",
          parent: 5,
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: {
              a: 1,
              k: [
                {
                  i: { x: [0.575], y: [9.237] },
                  o: { x: [0.333], y: [0] },
                  t: 9.2,
                  s: [36],
                },
                {
                  i: { x: [0.667], y: [1] },
                  o: { x: [0.341], y: [0.131] },
                  t: 11.6,
                  s: [37.298],
                },
                {
                  i: { x: [0.694], y: [-5.432] },
                  o: { x: [0.313], y: [0] },
                  t: 14,
                  s: [-28],
                },
                {
                  i: { x: [0.694], y: [1.152] },
                  o: { x: [0.342], y: [-0.17] },
                  t: 15.2,
                  s: [-28.99],
                },
                {
                  i: { x: [0.674], y: [0.55] },
                  o: { x: [0.342], y: [0.192] },
                  t: 15.6,
                  s: [-14.99],
                },
                {
                  i: { x: [0.673], y: [1.212] },
                  o: { x: [0.34], y: [1.235] },
                  t: 16,
                  s: [-27.367],
                },
                {
                  i: { x: [0.152], y: [1] },
                  o: { x: [0.343], y: [0.092] },
                  t: 16.4,
                  s: [-32.069],
                },
                {
                  i: { x: [0.575], y: [9.237] },
                  o: { x: [0.333], y: [0] },
                  t: 18.8,
                  s: [36],
                },
                {
                  i: { x: [0.667], y: [1] },
                  o: { x: [0.341], y: [0.164] },
                  t: 21.2,
                  s: [37.298],
                },
                {
                  i: { x: [0.694], y: [0.545] },
                  o: { x: [0.313], y: [0] },
                  t: 23.6,
                  s: [-15],
                },
                {
                  i: { x: [0.694], y: [1.152] },
                  o: { x: [0.342], y: [-0.17] },
                  t: 24.8,
                  s: [-28.99],
                },
                {
                  i: { x: [0.674], y: [0.55] },
                  o: { x: [0.342], y: [0.192] },
                  t: 25.2,
                  s: [-14.99],
                },
                {
                  i: { x: [0.673], y: [1.212] },
                  o: { x: [0.34], y: [1.235] },
                  t: 25.6,
                  s: [-27.367],
                },
                {
                  i: { x: [0.667], y: [1] },
                  o: { x: [0.343], y: [0.092] },
                  t: 26,
                  s: [-32.069],
                },
                { t: 28.4, s: [36] },
              ],
              ix: 10,
            },
            p: {
              a: 1,
              k: [
                {
                  i: { x: 0.833, y: 0.833 },
                  o: { x: 0.167, y: 0.167 },
                  t: 15.2,
                  s: [120.543, 159.552, 0],
                  to: [0, 0, 0],
                  ti: [0, 0, 0],
                },
                {
                  i: { x: 0.833, y: 0.833 },
                  o: { x: 0.167, y: 0.167 },
                  t: 15.6,
                  s: [102.935, 143.368, 0],
                  to: [0, 0, 0],
                  ti: [0, 0, 0],
                },
                {
                  i: { x: 0.833, y: 0.833 },
                  o: { x: 0.167, y: 0.167 },
                  t: 16,
                  s: [112.903, 154.794, 0],
                  to: [0, 0, 0],
                  ti: [0, 0, 0],
                },
                {
                  i: { x: 0.833, y: 0.833 },
                  o: { x: 0.167, y: 0.167 },
                  t: 24.8,
                  s: [120.543, 159.552, 0],
                  to: [0, 0, 0],
                  ti: [0, 0, 0],
                },
                {
                  i: { x: 0.833, y: 0.833 },
                  o: { x: 0.167, y: 0.167 },
                  t: 25.2,
                  s: [102.935, 143.368, 0],
                  to: [0, 0, 0],
                  ti: [0, 0, 0],
                },
                { t: 25.6, s: [112.903, 154.794, 0] },
              ],
              ix: 2,
              l: 2,
            },
            a: { a: 0, k: [54.719, 54.713, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          ip: 0,
          op: 120,
          st: 0,
          ct: 1,
          bm: 0,
        },
      ],
    },
  ],
  layer: {
    ddd: 0,
    ind: 6,
    ty: 0,
    nm: "back_leg",
    refId: "comp_7",
    sr: 1,
    ks: {
      o: { a: 0, k: 100, ix: 11 },
      r: { a: 0, k: 0, ix: 10 },
      p: { a: 0, k: [960, 540, 0], ix: 2, l: 2 },
      a: { a: 0, k: [960, 540, 0], ix: 1, l: 2 },
      s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
    },
    ao: 0,
    w: 1920,
    h: 1080,
    ip: 0,
    op: 10,
    st: 0,
    bm: 0,
  },
};
